format = """
[](#3B4252)\
$hostname\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
[](fg:#4C566A bg:#D08770)\
$git_state\
$cmd_duration\
[](fg:#D08770 bg:#86BBD8)\
$c$elixir$elm$golang$haskell$java$julia$nim$rust$php\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
$line_break$character
"""

command_timeout = 5000
# add_newline = false

[git_state]
style = "bg:#D08770 fg:#2E3440"
format = '[ $state( $progress_current/$progress_total) ]($style)'

[hostname]
ssh_only = true
style="bg:#3B4252"
format="[ $ssh_symbol$hostname ]($style)"

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[ ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind]($style)'

[c]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:#86BBD8 fg:#222222"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#06969A fg:#222222"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A"
format = '[ $time ]($style)'

[cmd_duration]
min_time = 500
style = "bg:#D08770 fg:#2E3440"
format = '[cmd took $duration ]($style)'
